version: 2.1

executors:
  docker-ex:
    docker:
      - image: circleci/node:10.10.0
    working_directory: ~/traktify

jobs:
  install:
    executor: docker-ex
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-

      - run: 
          name: Install npm dependencies
          command: |
            npm install

      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
    
  test:
    executor: docker-ex
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: 
          name: Run tests
          command: |
            npm run test

  build-deploy-docs:
    executor: docker-ex
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run:
          name: Build jsdoc
          command: |
            npm run build-docs

      - run:
          name: Clone docs target repo
          command: |
            git clone --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/CodingBobby/codingbobby.github.io.git
      
      - run:
          name: Deploy documentation
          command: |
            cd out
            git config credential.helper 'cache --timeout=120'
            git config user.email "bob.walter@outlook.de"
            git config user.name "Deployment Bot"
            git add docs
            git commit --allow-empty -m "Traktify Docs deployment"
            git push -q https://${DOCS_GITHUB_TOKEN}@github.com/CodingBobby/codingbobby.github.io.git master

workflows:
  version: 2.1
  build-test-deploy:
    jobs:
      - install

      - test:
          requires:
            - install

      - build-deploy-docs:
          requires:
            - install
