version: 2.1

executors:
  docker-ex:
    docker:
      - image: circleci/node:10.10.0
    working_directory: ~/traktify

jobs:
  install:
    executor: docker-ex
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-

      - run: 
          name: Install npm dependencies
          command: |
            npm install

      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
    
  test:
    executor: docker-ex
    steps:
      - checkout

      - run:
          name: Install test engine
          command: |
            npm i jest -g

      - run: 
          name: Run tests
          command: |
            npm run test

  build-docs:
    executor: docker-ex
    steps:
      - checkout

      - run:
          name: Install docs engine
          command: |
            npm i jsdoc -g

      - run:
          name: Build jsdoc
          command: |
            npm run build-docs
  
  deploy-docs:
    executor: docker-ex
    steps:
      - checkout

      - run:
          name: Deploy documentation
          command: |
            cd out
            git config credential.helper 'cache --timeout=120'
            git config user.email "bob.walter@outlook.de"
            git config user.name "Deployment Bot"
            git add docs
            git commit --allow-empty -m "Traktify Docs deployment"
            git push -q https://${DOCS_GITHUB_TOKEN}@github.com/CodingBobby/codingbobby.github.io.git master

workflows:
  version: 2.1
  build-test-deploy:
    jobs:
      - install

      - test:
          requires:
            - install

      - build-docs:
          requires:
            - install

      - deploy-docs:
          requires:
            - install
            - build-docs
