version: 2.1

executors:
  docker-ex:
    docker:
      - image: circleci/node:10.10.0
    working_directory: ~/traktify

jobs:
  install:
    executor: docker-ex
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-

      - run: 
          name: Install npm dependencies
          command: |
            npm install

      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
    
  test:
    executor: docker-ex
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: 
          name: Run tests
          command: |
            npm run test

workflows:
  version: 2.1
  build-test-deploy:
    jobs:
      - install

      - test:
          requires:
            - install
